name: project_timeline
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble_tab_indicator: ^0.1.4
  carousel_pro: ^1.0.0
  carousel_slider: ^2.3.1
  clay_containers: ^0.2.2
  cloud_firestore: ^0.12.9+4
  cupertino_icons: ^0.1.3
  fancy_bottom_navigation: ^0.3.2
  # firebase_auth: ^0.16.1
  # firebase_core: ^0.4.5
  # firebase_database: ^3.1.6
  # firebase_storage: ^3.0.3
  flip_card: ^0.4.4
  flutter_absolute_path: ^1.0.6
  flutter_full_pdf_viewer: ^1.0.6
  flutter_pdfview: ^1.0.0
  flutter_phoenix: ^0.1.0
  flutter_sms: ^2.0.1+2
  flutter_time_picker_spinner: ^1.0.6+1
  fluttertoast: ^7.0.2
  font_awesome_flutter: ^8.8.1
  geocoder: ^0.2.1
  google_fonts: ^1.1.1
  # google_maps_flutter: ^1.0.3
  groovin_widgets: ^1.6.0
  grouped_list: ^3.3.0
  intl: ^0.16.1
  intro_slider: ^2.3.3
  link: ^1.1.0
  multi_image_picker: ^4.7.13
  path_provider: ^1.6.16
  pdf: ^1.10.0
  percent_indicator: ^2.1.5
  photo_view: ^0.10.2
  printing: ^3.6.1
  progress_dialog: ^1.2.4
  provider: ^4.3.2+2
  random_string: ^2.1.0
  searchable_dropdown: ^1.1.3
  shared_preferences: ^0.5.12+2
  time_formatter: ^1.0.0+5
  translator: ^0.1.5
  uuid: ^2.2.0


  razorpay_flutter: ^1.2.1
  http: ^0.12.0+4
  confetti: ^0.5.4+1
  hexcolor: ^1.0.6





  # http: ^0.12.2
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_storage: ^4.0.0
  file_picker: ^1.13.3
  firebase_database: ^4.0.0
  # time_formatter: ^1.0.0+5
  # intl: ^0.16.1
  flutter_downloader: ^1.5.0
  dio: ^3.0.10
  # path_provider: ^1.6.14
  path: ^1.7.0
  permission_handler: ^5.0.1+1
  # font_awesome_flutter: ^8.8.1
  url_launcher: ^5.5.2
  auto_size_text: ^2.1.0
  # provider: ^4.3.2+2
  flutter_spinkit: ^4.1.2+1
  share: ^0.6.5+2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
